/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ikarabulut;

public class App {

    public static void main(String[] args) {
        Board board = new Board();
        board.setGrid();
        System.out.println(board.getGrid());
    }
}
